name: first
on: [pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run prepare
      - run: npm run run
      - run: npm run test
  format:
    # Check if the PR is not from a fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: install packages
        run: npm install
      - name: formatting
        run: npm run fix
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: output
        run: cat "$GITHUB_OUTPUT"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo ${{ secrets.TOKEN }}
          git config --global user.name 'HakimHC'
          git config --global user.email 'ahmedh90111@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated changes"
          git push
